# Generated by Django 4.2.1 on 2023-05-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
