# Generated by Django 4.2.1 on 2023-05-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
